import Head from "next/head";
import Card from "../components/Card";
import Navbar from "../components/Navbar";
import { AiOutlineArrowRight } from "react-icons/ai";
import Image from "next/image";
import Img from "../assets/img/image2.png";

// dummy data
import { FEATURED_STORIES } from "../assets/data/Database";
import Card2 from "../components/Card2";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next js Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="h-[120px]"></div>
        <div className="wrapper">
          <h3 className="title border-b">FEATURED STORIES</h3>
          <div className="py-4 mt-2 grid xl:grid-cols-2 gap-6">
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
          </div>
          <br />
          <br />
          <div className="border-b flex justify-between items-center">
            <h3 className="title">LATEST NEWS</h3>
            <a
              href="#"
              className="text-indigo-500 font-semibold flex items-center gap-3 hover:text-indigo-400"
            >
              View all <AiOutlineArrowRight />
            </a>
          </div>
          <div className="py-4 mt-2 grid xl:grid-cols-2 gap-6">
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
          </div>
          <br />
          <br />
          <div>
            <h3 className="title border-b">SPOTLIGHT</h3>
            <div className="py-6 grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-y-6">
              <Image
                className="w-[180px] xl:w-[300px] hover:opacity-75 cursor-pointer rounded-lg"
                src={Img}
                alt=""
              />
              <Image
                className="w-[180px] xl:w-[300px] hover:opacity-75 cursor-pointer rounded-lg"
                src={Img}
                alt=""
              />
              <Image
                className="w-[180px] xl:w-[300px] hover:opacity-75 cursor-pointer rounded-lg"
                src={Img}
                alt=""
              />
              <Image
                className="w-[180px] xl:w-[300px] hover:opacity-75 cursor-pointer rounded-lg"
                src={Img}
                alt=""
              />
            </div>
          </div>
          <br />
          <br />
          <div>
            <h3 className="title border-b">IN CONVERSATION</h3>
            <div>
              {FEATURED_STORIES.map((data, index) => (
                <Card2 key={index} data={data} />
              ))}
            </div>
          </div>

          <br />
          <br />

          <h3 className="title border-b">THROUGH MY EYES</h3>
          <div className="py-4 mt-2 grid xl:grid-cols-2 gap-6">
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
          </div>
          <br />
          <br />
          <h3 className="title border-b">PAST HEADLINES</h3>
          <div className="py-4 mt-2 grid xl:grid-cols-2 gap-6">
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
          </div>
          <br />
          <br />
          <div>
            <h3 className="title border-b">MEDICAL MYTHS</h3>
            <div>
              {FEATURED_STORIES.map((data, index) => (
                <Card2 key={index} data={data} />
              ))}
            </div>
          </div>
        </div>
      </main>
      <div className="h-[100px]"></div>
      <Footer />
    </div>
  );
}
