import Head from "next/head";
import Card from "../components/Card";
import Navbar from "../components/Navbar";
import { AiOutlineArrowRight } from "react-icons/ai";

// dummy data
import { FEATURED_STORIES } from "../assets/data/Database";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next js Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="h-[120px]"></div>
        <div className="wrapper">
          <h3 className="title border-b">FEATURED STORIES</h3>
          <div className="py-4 mt-2 grid xl:grid-cols-2 gap-6">
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
          </div>
          <br />
          <br />
          <div className="border-b flex justify-between items-center">
            <h3 className="title">LATEST NEWS</h3>
            <a
              href="#"
              className="text-indigo-500 font-semibold flex items-center gap-3 hover:text-indigo-400"
            >
              View all <AiOutlineArrowRight />
            </a>
          </div>
          <div className="py-4 mt-2 grid xl:grid-cols-2 gap-6">
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
            {FEATURED_STORIES.map((data, index) => (
              <Card key={index} data={data} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
